insertdictk = ['Category1', 'Category2', '`Condition`', 'ConditionBewrite', 'Quantity', 'LotSize',
                   'Duration', 'ReservePrice', 'BestOffer', '`BestOfferAutoAcceptPrice`', '`BestOfferAutoRefusedPrice`',
                   'AcceptPayment', 'PayPalEmailAddress',
                   'Location', 'LocationCountry', 'ReturnsAccepted', 'RefundOptions', 'ReturnsWithin',
                   'ReturnPolicyShippingCostPaidBy', 'ReturnPolicyDescription',
                   'GalleryType', 'Bold', 'PrivateListing', 'HitCounter', 'sku', 'PictureURL', 'Title', 'SubTitle',
                   'IbayCategory', 'StartPrice', 'BuyItNowPrice', 'other_itemnum',
                   'ShippingService1', 'ShippingServiceCost1', 'ShippingServiceAdditionalCost1', 'ShippingService2',
                   'ShippingServiceCost2', 'ShippingServiceAdditionalCost2',
                   'ShippingService3', 'ShippingServiceCost3', 'ShippingServiceAdditionalCost3', 'ShippingService4',
                   'ShippingServiceCost4', 'ShippingServiceAdditionalCost4',
                   'InternationalShippingService1', 'InternationalShippingServiceCost1',
                   'InternationalShippingServiceAdditionalCost1', 'InternationalShipToLocation1',
                   'InternationalShippingService2', 'InternationalShippingServiceCost2',
                   'InternationalShippingServiceAdditionalCost2', 'InternationalShipToLocation2',
                   'InternationalShippingService3', 'InternationalShippingServiceCost3',
                   'InternationalShippingServiceAdditionalCost3', 'InternationalShipToLocation3',
                   'InternationalShippingService4', 'InternationalShippingServiceCost4',
                   'InternationalShippingServiceAdditionalCost4', 'InternationalShipToLocation4',
                   'InternationalShippingService5', 'InternationalShippingServiceCost5',
                   'InternationalShippingServiceAdditionalCost5', 'InternationalShipToLocation5',
                   'DispatchTimeMax', 'ExcludeShipToLocation', 'StoreCategory1', 'StoreCategory2', 'IbayTemplate',
                   'IbayInformation', 'IbayComment', 'Description', '`Language`',
                   'IbayOnlineInventoryHold', 'IbayRelistSold', 'IbayRelistUnsold', 'IBayEffectType', 'IbayEffectImg',
                   'IbayCrossSelling', 'Variation', 'outofstockcontrol', 'EPID',
                   'ISBN', 'UPC', 'EAN', 'SecondOffer', 'ImmediatelyPay', 'Currency', 'LinkedPayPalAccount',
                   'MBPVCount', 'MBPVPeriod', 'MUISICount', 'MUISIPeriod', 'MaximumItemCount',
                   'MinimumFeedbackScore', 'Specifics1', 'Specifics2', 'Specifics3', 'Specifics4', 'Specifics5',
                   'Specifics6', 'Specifics7', 'Specifics8', 'Specifics9', 'Specifics10',
                   'Specifics11', 'Specifics12', 'Specifics13', 'Specifics14', 'Specifics15', 'Specifics16',
                   'Specifics17', 'Specifics18', 'Specifics19', 'Specifics20', 'Specifics21', 'Specifics22',
                   'Specifics23', 'Specifics24', 'Specifics25', 'Specifics26', 'Specifics27', 'Specifics28',
                   'Specifics29', 'Specifics30', 'Images', 'CreateTime', 'CreateStaff', 'UpdateTime', 'UpdateStaff',
                   'CoreWords', 'OssUrl', 'Flag', 'ExcelFile', '`Status`', 'variationSpecificsSet']