# -*- coding: utf-8 -*-
from django.db import models
from public import getChoices,ChoiceUnit,ChoiceIF
from django.utils.safestring import mark_safe

class t_product_build_FBA(models.Model):
    id = models.AutoField(u'业务流水号', primary_key=True)
    SKU = models.CharField(u'FBA_SKU', max_length=32, blank=False, null=False)
    OldSKU = models.CharField(u'SKU', max_length=32, blank=True, null=True)
    MainSKU = models.CharField(u'主SKU*', max_length=255, blank=True, null=True)
    LargeCategory = models.CharField(u'大类名称', max_length=32, blank=True, null=False)
    SmallCategory = models.CharField(u'小类名称',  max_length=32, blank=True, null=False)
    Name2 = models.CharField(mark_safe(u'商品名称<br>(中文)'), max_length=128, blank=True, null=True)
    GoodsStatus = models.CharField(u'商品状态', max_length=32, default='正常', null=True)
    Material = models.CharField(u'材质', max_length=32, blank=True, null=True)
    Model = models.CharField(u'型号', max_length=32, blank=True, null=True)
    Brand = models.CharField(u'品牌', max_length=32, blank=True, null=True)
    Unit = models.CharField(u'单位', choices=getChoices(ChoiceUnit), default=0,max_length=32, blank=True, null=True)
    MinPackNum = models.PositiveSmallIntegerField(mark_safe(u'最小包<br>装数量'), blank=True, null=True)
    Weight = models.DecimalField(u'重量(g)', max_digits=6, decimal_places=2, blank=True, null=True)
    SupplierName = models.CharField(mark_safe(u'供应商名称'), max_length=32, blank=True, null=True)
    CostPrice = models.DecimalField(u'成本单价(¥元)', max_digits=6, decimal_places=2, blank=True, null=True)
    Remark = models.TextField(u'备注', blank=True, null=True)
    ReportName2 = models.CharField(u'中文申报名', max_length=32, blank=True, null=True)
    ReportName = models.CharField(u'英文申报名', max_length=32, blank=True, null=True)
    DeclaredValue = models.DecimalField(u'申报价值(美元)', max_digits=6, decimal_places=2, blank=True, null=True)
    OriginCountryCode = models.CharField(u'原产国代码', max_length=16, blank=True, null=True)
    OriginCountry = models.CharField(u'原产国', max_length=32, blank=True, null=True)
    MaxNum = models.PositiveSmallIntegerField(u'库存上限',blank=True, null=True)
    MinNum = models.PositiveSmallIntegerField(u'库存下限',blank=True, null=True)
    SalerName = models.CharField(u'业绩归属人', max_length=16, blank=True, null=True)
    SalerName2 = models.CharField(u'业绩归属人2', max_length=16, blank=True, null=True)
    PackingID = models.CharField(u'包装规格', max_length=32, blank=True, null=True)
    DevDate = models.DateField(u'开发日期', blank = True,null = True)
    Purchaser = models.CharField(u'采购员', max_length=16, blank=True, null=True)
    Storehouse = models.CharField(u'发货仓库', max_length=16, default=u'亚马逊仓库',blank=True, null=True)
    StockDays = models.PositiveSmallIntegerField(u'采购到货天数', blank=True, null=True)
    InnerPrice = models.DecimalField(u'内包装成本', max_digits=6, decimal_places=2, blank=True, null=True)
    LinkUrl = models.CharField(u'网页URL', max_length=256,blank=True, null=True)
    LinkUrl2 = models.CharField(u'网页URL2', max_length=256,blank=True, null=True)
    SellDays = models.PositiveSmallIntegerField(u'库存预警天数', blank=True, null=True)
    StockMinAmount = models.PositiveSmallIntegerField(u'采购最小订货量', blank=True, null=True)
    Electrification = models.CharField(u'是否带电', choices=getChoices(ChoiceIF), max_length=4, default=u'否', blank=True,null=True)
    Powder = models.CharField(u'是否粉末', choices=getChoices(ChoiceIF), max_length=4, default=u'否', blank=True, null=True)
    Liquid = models.CharField(u'是否液体', choices=getChoices(ChoiceIF), max_length=4, default=u'否', blank=True, null=True)
    possessMan1 = models.CharField(u'责任归属人1', max_length=16, blank=True, null=True)
    possessMan2 = models.CharField(u'责任归属人2', max_length=16, blank=True, null=True)
    ContrabandAttribute = models.CharField(u'商品属性', default=u'普货', max_length=16, blank=True, null=True)
    DegreeOfDifficulty = models.CharField(u'包装难度系数',  max_length=16, blank=True, null=True)
    ShopName = models.CharField(u'店铺名称', max_length=128, blank=True, null=True)
    LinkUrl4 = models.CharField(u'网页URL4', max_length=256,blank=True, null=True)
    LinkUrl5 = models.CharField(u'网页URL5', max_length=256,blank=True, null=True)
    LinkUrl6 = models.CharField(u'网页URL6', max_length=256,blank=True, null=True)
    ShopFreight = models.DecimalField(u'店铺运费', max_digits=6, decimal_places=2, blank=True, null=True)
    PackWeight = models.DecimalField(u'包装材料重量', max_digits=6, decimal_places=2, blank=True, null=True)
    ExchangeRate = models.DecimalField(u'汇率', max_digits=6, decimal_places=2, blank=True, null=True)
    LogisticsPrice = models.DecimalField(u'物流公司价格', max_digits=6, decimal_places=2, blank=True, null=True)
    TransactionFee = models.DecimalField(u'交易费', max_digits=6, decimal_places=2, blank=True, null=True)
    ProfitRate = models.DecimalField(u'毛利率', max_digits=6, decimal_places=2, blank=True, null=True)
    SellingPrice = models.DecimalField(u'计算售价', max_digits=6, decimal_places=2, blank=True, null=True)
    LRTime = models.DateTimeField(u'录入时间', blank=True, null=True)
    LRStaffName = models.CharField(u'录入员', max_length=16, blank=True, null=True)
    isflag = models.PositiveSmallIntegerField(u'FBA流程标志', blank=True, null=True,default=0)
    FBAFinshTime = models.DateTimeField(u'FBA录入完成时间', blank=True, null=True)
    MultiStyle = models.PositiveSmallIntegerField(u'多款式', blank=True, null=True, default=0)
    SampleFlag = models.PositiveSmallIntegerField(u'是否有样品', blank=True, null=True, default=0)
    SampleCount = models.PositiveSmallIntegerField(u'样品数量', blank=True, null=True, default=0)
    Class = models.CharField(u'规格', max_length=256, blank=True, null=True)
    Style = models.CharField(u'款式', max_length=256, blank=True, null=True)
    BarCode = models.CharField(u'采购渠道', max_length=128, blank=True, null=True)
    BatchPrice = models.DecimalField(u'批发价格(美元)', max_digits=6, decimal_places=2, blank=True, null=True)
    RetailPrice = models.DecimalField(u'零售价格-美元', max_digits=6, decimal_places=2, blank=True, null=True)
    SalePrice = models.DecimalField(u'最低售价(美元)', max_digits=6, decimal_places=2, blank=True, null=True)
    MaxSalePrice = models.DecimalField(u'最高售价(美元)', max_digits=6, decimal_places=2, blank=True, null=True)
    MarketPrice = models.DecimalField(u'市场参考价(美元)', max_digits=6, decimal_places=2, blank=True, null=True)
    Quantity = models.PositiveSmallIntegerField(u'数量', blank=True, null=True, default=0)

    SKUStyle1 = models.CharField(u'SKU款式1', max_length=128, blank=True, null=True)
    SKUStyle2 = models.CharField(u'SKU款式2', max_length=128, blank=True, null=True)
    SKUStyle3 = models.CharField(u'SKU款式3', max_length=128, blank=True, null=True)
    SKUDescribe = models.CharField(u'SKU描述', max_length=256, blank=True, null=True)
    BmpUrl = models.CharField(u'图片URL', max_length=256, blank=True, null=True)
    LinkUrl3 = models.CharField(u'网页URL3', max_length=256, blank=True, null=True)
    MinPrice = models.DecimalField(u'最低采购价格', max_digits=6, decimal_places=2, blank=True, null=True)
    HSCODE = models.CharField(u'海关编码', max_length=64, blank=True, null=True)
    InLong = models.DecimalField(u'内盒长', max_digits=6, decimal_places=2, blank=True, null=True)
    InWide = models.DecimalField(u'内盒宽', max_digits=6, decimal_places=2, blank=True, null=True)
    InHigh = models.DecimalField(u'内盒高', max_digits=6, decimal_places=2, blank=True, null=True)
    InGrossweight = models.DecimalField(u'内盒毛重', max_digits=6, decimal_places=2, blank=True, null=True)
    InNetweight = models.DecimalField(u'内盒净重', max_digits=6, decimal_places=2, blank=True, null=True)
    OutLong = models.DecimalField(u'外箱长', max_digits=6, decimal_places=2, blank=True, null=True)
    OutWide = models.DecimalField(u'外箱宽', max_digits=6, decimal_places=2, blank=True, null=True)
    OutHigh = models.DecimalField(u'外箱高', max_digits=6, decimal_places=2, blank=True, null=True)
    OutGrossweight = models.DecimalField(u'外箱毛重', max_digits=6, decimal_places=2, blank=True, null=True)
    OutNetweight = models.DecimalField(u'外箱净重', max_digits=6, decimal_places=2, blank=True, null=True)
    ItemUrl = models.CharField(u'商品URL', max_length=256, blank=True, null=True)
    PackMsg = models.CharField(u'包装事项', max_length=256, blank=True, null=True)
    JobPower = models.CharField(u'工号权限', max_length=128, blank=True, null=True)
    Season = models.CharField(u'季节', max_length=100, blank=True, null=True)
    OpDatetime = models.DateTimeField(u'操作时间', blank=True, null=True)
    OpStaffName = models.CharField(u'操作员', max_length=16, blank=True, null=True)
    auditnote = models.TextField(u'审核员备注', blank=True, null=True)
    class Meta:
        verbose_name = u'FBA-建资料'
        verbose_name_plural = verbose_name
        db_table = "t_product_build_fba"
    def __unicode__(self):
        return u'id:%s,FBA-sku:%s'%(self.id,self.SKU)
