# -*- coding: utf-8 -*-

from django.db import models
from django.utils.safestring import mark_safe

class t_templet_ebay_base(models.Model):
    Category1 = models.CharField(u'eBay分类', max_length=64, blank=True, null=True)
    Category2 = models.CharField(u'ebay分类2', max_length=64, blank=True, null=True)
    Condition = models.CharField(u'产品条件', max_length=64, blank=True, null=True)
    ConditionBewrite = models.CharField(u'产品条件', max_length=64, blank=True, null=True)
    Quantity = models.CharField(u'数量', max_length=64, blank=True, null=True)
    LotSize = models.CharField(u'批量', max_length=64, blank=True, null=True)
    Duration = models.CharField(u'持续时间', max_length=64, blank=True, null=True)
    ReservePrice = models.CharField(u'储备价格', max_length=64, blank=True, null=True)
    BestOffer = models.CharField(u'最佳报价', max_length=64, blank=True, null=True)
    BestOfferAutoAcceptPrice = models.CharField(u'默认接受价格', max_length=64, blank=True, null=True)
    BestOfferAutoRefusedPrice = models.CharField(u'默认拒绝价格', max_length=64, blank=True, null=True)
    AcceptPayment = models.CharField(u'支付手段', max_length=64, blank=True, null=True)
    PayPalEmailAddress = models.CharField(u'收款账号', max_length=64, blank=True, null=True)
    Location = models.CharField(u'城市', max_length=64, blank=True, null=True)
    LocationCountry = models.CharField(u'国家', max_length=64, blank=True, null=True)
    ReturnsAccepted = models.CharField(u'是否接受退款', max_length=64, blank=True, null=True)
    RefundOptions = models.CharField(u'退款方式', max_length=64, blank=True, null=True)
    ReturnsWithin = models.CharField(u'退款期限', max_length=64, blank=True, null=True)
    ReturnPolicyShippingCostPaidBy = models.CharField(u'运费承担者', max_length=64, blank=True, null=True)
    ReturnPolicyDescription = models.TextField(u'售后详情', blank=True, null=True)
    GalleryType = models.CharField(u'橱窗形式', max_length=64, blank=True, null=True)
    Bold = models.CharField(u'样式', max_length=64, blank=True, null=True)
    PrivateListing = models.CharField(u'匿名购买', max_length=64, blank=True, null=True)
    HitCounter = models.CharField(u'计数器', max_length=64, blank=True, null=True)
    sku = models.CharField(u'SKU', max_length=64, blank=True, null=True)
    PictureURL = models.TextField(u'图片', blank=True, null=True)
    Title = models.TextField(u'标题', blank=True, null=True)
    SubTitle = models.CharField(u'副标题', max_length=64, blank=True, null=True)
    IbayCategory = models.CharField(u'ibay分类', max_length=64, blank=True, null=True)
    StartPrice = models.CharField(u'起拍价', max_length=64, blank=True, null=True)
    BuyItNowPrice = models.CharField(u'一口价', max_length=64, blank=True, null=True)
    other_itemnum = models.CharField(u'其他', max_length=64, blank=True, null=True)
    ShippingService1 = models.CharField(u'货运方式1', max_length=64, blank=True, null=True)
    ShippingServiceCost1 = models.CharField(u'首件运费', max_length=64, blank=True, null=True)
    ShippingServiceAdditionalCost1 = models.CharField(u'第二件运费', max_length=64, blank=True, null=True)
    ShippingService2 = models.CharField(u'货运方式2', max_length=64, blank=True, null=True)
    ShippingServiceCost2 = models.CharField(u'首件运费2', max_length=64, blank=True, null=True)
    ShippingServiceAdditionalCost2 = models.CharField(u'第二件运费2', max_length=64, blank=True, null=True)
    ShippingService3 = models.CharField(u'货运方式3', max_length=64, blank=True, null=True)
    ShippingServiceCost3 = models.CharField(u'首件运费3', max_length=64, blank=True, null=True)
    ShippingServiceAdditionalCost3 = models.CharField(u'第二件运费3', max_length=64, blank=True, null=True)
    ShippingService4 = models.CharField(u'货运方式4', max_length=64, blank=True, null=True)
    ShippingServiceCost4 = models.CharField(u'首件运费4', max_length=64, blank=True, null=True)
    ShippingServiceAdditionalCost4 = models.CharField(u'第二件运费4', max_length=64, blank=True, null=True)
    InternationalShippingService1 = models.CharField(u'境外物流', max_length=64, blank=True, null=True)
    InternationalShippingServiceCost1 = models.CharField(u'境外首件运费', max_length=64, blank=True, null=True)
    InternationalShippingServiceAdditionalCost1 = models.CharField(u'境外第二件运费', max_length=64, blank=True, null=True)
    InternationalShipToLocation1 = models.CharField(u'境外全球货运', max_length=64, blank=True, null=True)
    InternationalShippingService2 = models.CharField(u'境外物流2', max_length=64, blank=True, null=True)
    InternationalShippingServiceCost2 = models.CharField(u'境外首件运费2', max_length=64, blank=True, null=True)
    InternationalShippingServiceAdditionalCost2 = models.CharField(u'境外第二件运费2', max_length=64, blank=True, null=True)
    InternationalShipToLocation2 = models.CharField(u'境外全球货运2', max_length=64, blank=True, null=True)
    InternationalShippingService3 = models.CharField(u'境外物流3', max_length=64, blank=True, null=True)
    InternationalShippingServiceCost3 = models.CharField(u'境外首件运费3', max_length=64, blank=True, null=True)
    InternationalShippingServiceAdditionalCost3 = models.CharField(u'境外第二件运费3', max_length=64, blank=True, null=True)
    InternationalShipToLocation3 = models.CharField(u'境外全球货运3', max_length=64, blank=True, null=True)
    InternationalShippingService4 = models.CharField(u'境外物流4', max_length=64, blank=True, null=True)
    InternationalShippingServiceCost4 = models.CharField(u'境外首件运费4', max_length=64, blank=True, null=True)
    InternationalShippingServiceAdditionalCost4 = models.CharField(u'境外第二件运费4', max_length=64, blank=True, null=True)
    InternationalShipToLocation4 = models.CharField(u'境外全球货运4', max_length=64, blank=True, null=True)
    InternationalShippingService5 = models.CharField(u'境外物流5', max_length=64, blank=True, null=True)
    InternationalShippingServiceCost5 = models.CharField(u'境外首件运费5', max_length=64, blank=True, null=True)
    InternationalShippingServiceAdditionalCost5 = models.CharField(u'境外第二件运费5', max_length=64, blank=True, null=True)
    InternationalShipToLocation5 = models.CharField(u'境外全球货运5', max_length=64, blank=True, null=True)
    DispatchTimeMax = models.CharField(u'备货时间', max_length=64, blank=True, null=True)
    ExcludeShipToLocation = models.TextField(u'屏蔽货运目的地', blank=True, null=True)
    StoreCategory1 = models.CharField(u'店铺类目1', max_length=64, blank=True, null=True)
    StoreCategory2 = models.CharField(u'店铺类目2', max_length=64, blank=True, null=True)
    IbayTemplate = models.CharField(u'店铺风格', max_length=64, blank=True, null=True)
    IbayInformation = models.CharField(u'ibay信息', max_length=64, blank=True, null=True)
    IbayComment = models.CharField(u'ibay备注', max_length=64, blank=True, null=True)
    Description = models.TextField(u'描述', blank=True, null=True)
    Language = models.CharField(u'语言', max_length=64, blank=True, null=True)
    IbayOnlineInventoryHold = models.CharField(u'保留库存', max_length=64, blank=True, null=True)
    IbayRelistSold = models.CharField(u'已售', max_length=64, blank=True, null=True)
    IbayRelistUnsold = models.CharField(u'未售', max_length=64, blank=True, null=True)
    IBayEffectType = models.CharField(u'ibay效果图类型', max_length=64, blank=True, null=True)
    IbayEffectImg = models.CharField(u'ibay效果图', max_length=64, blank=True, null=True)
    IbayCrossSelling = models.CharField(u'交叉销售', max_length=64, blank=True, null=True)
    Variation = models.TextField(u'多属性变量', blank=True, null=True)
    outofstockcontrol = models.CharField(u'自动补货', max_length=64, blank=True, null=True)
    EPID = models.CharField(u'全球贸易项目代码EPID', max_length=64, blank=True, null=True)
    ISBN = models.CharField(u'全球贸易项目代码ISBN', max_length=64, blank=True, null=True)
    UPC = models.CharField(u'全球贸易项目代码UPC', max_length=64, blank=True, null=True)
    EAN = models.CharField(u'全球贸易项目代码EAN', max_length=64, blank=True, null=True)
    SecondOffer = models.CharField(u'二次报价', max_length=64, blank=True, null=True)
    ImmediatelyPay = models.CharField(u'立即付款', max_length=64, blank=True, null=True)
    Currency = models.CharField(u'货币代码', max_length=64, blank=True, null=True)
    LinkedPayPalAccount = models.CharField(u'关联PayPal账户', max_length=64, blank=True, null=True)
    MBPVCount = models.CharField(u'MBPV数量', max_length=64, blank=True, null=True)
    MBPVPeriod = models.CharField(u'MBPV期', max_length=64, blank=True, null=True)
    MUISICount = models.CharField(u'MUISI数量', max_length=64, blank=True, null=True)
    MUISIPeriod = models.CharField(u'MUISI期', max_length=64, blank=True, null=True)
    MaximumItemCount = models.CharField(u'最大物品数量', max_length=64, blank=True, null=True)
    MinimumFeedbackScore = models.CharField(u'最低反馈分数', max_length=64, blank=True, null=True)
    listingcategory_id = models.CharField(u'listingcategory_id',max_length=64, blank=True, null=True)
    Specifics1 = models.TextField(u'结构化描述', blank=True, null=True)
    Specifics2 = models.TextField(u'结构化描述2', blank=True, null=True)
    Specifics3 = models.TextField(u'结构化描述3', blank=True, null=True)
    Specifics4 = models.TextField(u'结构化描述4', blank=True, null=True)
    Specifics5 = models.TextField(u'结构化描述5', blank=True, null=True)
    Specifics6 = models.TextField(u'结构化描述6', blank=True, null=True)
    Specifics7 = models.TextField(u'结构化描述7', blank=True, null=True)
    Specifics8 = models.TextField(u'结构化描述8', blank=True, null=True)
    Specifics9 = models.TextField(u'结构化描述9', blank=True, null=True)
    Specifics10 = models.TextField(u'结构化描述10', blank=True, null=True)
    Specifics11 = models.TextField(u'结构化描述11', blank=True, null=True)
    Specifics12 = models.TextField(u'结构化描述12', blank=True, null=True)
    Specifics13 = models.TextField(u'结构化描述13', blank=True, null=True)
    Specifics14 = models.TextField(u'结构化描述14', blank=True, null=True)
    Specifics15 = models.TextField(u'结构化描述15', blank=True, null=True)
    Specifics16 = models.TextField(u'结构化描述16', blank=True, null=True)
    Specifics17 = models.TextField(u'结构化描述17', blank=True, null=True)
    Specifics18 = models.TextField(u'结构化描述18', blank=True, null=True)
    Specifics19 = models.TextField(u'结构化描述19', blank=True, null=True)
    Specifics20 = models.TextField(u'结构化描述20', blank=True, null=True)
    Specifics21 = models.TextField(u'结构化描述21', blank=True, null=True)
    Specifics22 = models.TextField(u'结构化描述22', blank=True, null=True)
    Specifics23 = models.TextField(u'结构化描述23', blank=True, null=True)
    Specifics24 = models.TextField(u'结构化描述24', blank=True, null=True)
    Specifics25 = models.TextField(u'结构化描述25', blank=True, null=True)
    Specifics26 = models.TextField(u'结构化描述26', blank=True, null=True)
    Specifics27 = models.TextField(u'结构化描述27', blank=True, null=True)
    Specifics28 = models.TextField(u'结构化描述28', blank=True, null=True)
    Specifics29 = models.TextField(u'结构化描述29', blank=True, null=True)
    Specifics30 = models.TextField(u'结构化描述30', blank=True, null=True)

    CreateTime = models.DateTimeField(u'采集时间', blank=True, null=True)
    CreateStaff = models.CharField(u'采集人', max_length=16, blank=True, null=True)
    UpdateTime = models.DateTimeField(u'更新时间', blank=True, null=True)
    UpdateStaff = models.CharField(u'更新人', max_length=16, blank=True, null=True)
    OssUrl = models.CharField(u'OSS压缩包地址', max_length=255, blank=True, null=True)
    CoreWords = models.TextField(u'核心标题', blank=True, null=True)
    Flag = models.IntegerField(u'显示标识', max_length=2, blank=True, null=True)
    Status = models.CharField(u'状态', max_length=32, blank=True, null=True)
    ExcelFile = models.FileField(u'采集数据导入',blank = True,null = True)

    variationSpecificsSet = models.TextField(u'多属性变量类型', blank=True, null=True)
    Images = models.TextField(u'商品主图', blank=True, null=True)

    Site = models.IntegerField(u'站点', max_length=32, blank=True, null=True)
    Selleruserid = models.CharField(u'销售', max_length=64, blank=True, null=True)
    Seller = models.CharField(u'店铺管理员', max_length=255, blank=True, null=True)

    class Meta:
        app_label = 'skuapp'
        abstract = True
    def __unicode__(self):
        return u'id:%s'% (self.id)